<?php

namespace Database\Seeders;

use App\Models\Pokemon;
use Illuminate\Database\Seeder;

class PokemonSeeder extends Seeder
{
    /**
     * Llena la base de datos local con los 20 Pokémon requeridos de Kanto,
     * incluyendo estadísticas oficiales, tipos en español, medidas y descripciones
     * de Pokémon Rojo Fuego para permitir el funcionamiento 100% offline.
     */
    public function run(): void
    {
        $pokemons = [
            [
                'id' => 1,
                'name' => 'bulbasaur',
                'genus' => 'Pokémon Semilla',
                'height' => 0.7,
                'weight' => 6.9,
                'sprite' => '/images/sprites/1.png',
                'types' => [
                    ['key' => 'grass', 'name' => 'PLANTA'],
                    ['key' => 'poison', 'name' => 'VENENO'],
                ],
                'description' => 'Una rara semilla le fue plantada en el lomo al nacer. La planta brota y crece con este Pokémon.',
                'hp' => 45,
                'attack' => 49,
                'defense' => 49,
                'special_attack' => 65,
                'special_defense' => 65,
                'speed' => 45,
            ],
            [
                'id' => 2,
                'name' => 'ivysaur',
                'genus' => 'Pokémon Semilla',
                'height' => 1.0,
                'weight' => 13.0,
                'sprite' => '/images/sprites/2.png',
                'types' => [
                    ['key' => 'grass', 'name' => 'PLANTA'],
                    ['key' => 'poison', 'name' => 'VENENO'],
                ],
                'description' => 'Cuando la flor de su lomo está a punto de abrirse, empieza a despedir un dulce aroma floral.',
                'hp' => 60,
                'attack' => 62,
                'defense' => 63,
                'special_attack' => 80,
                'special_defense' => 80,
                'speed' => 60,
            ],
            [
                'id' => 3,
                'name' => 'venusaur',
                'genus' => 'Pokémon Semilla',
                'height' => 2.0,
                'weight' => 100.0,
                'sprite' => '/images/sprites/3.png',
                'types' => [
                    ['key' => 'grass', 'name' => 'PLANTA'],
                    ['key' => 'poison', 'name' => 'VENENO'],
                ],
                'description' => 'La enorme flor que tiene en la espalda absorbe los rayos de sol para convertirlos en energía vital.',
                'hp' => 80,
                'attack' => 82,
                'defense' => 83,
                'special_attack' => 100,
                'special_defense' => 100,
                'speed' => 80,
            ],
            [
                'id' => 4,
                'name' => 'charmander',
                'genus' => 'Pokémon Lagartija',
                'height' => 0.6,
                'weight' => 8.5,
                'sprite' => '/images/sprites/4.png',
                'types' => [
                    ['key' => 'fire', 'name' => 'FUEGO'],
                ],
                'description' => 'La llama que tiene en la punta de la cola arde según sus sentimientos. Llamea suavemente si está alegre.',
                'hp' => 39,
                'attack' => 52,
                'defense' => 43,
                'special_attack' => 60,
                'special_defense' => 50,
                'speed' => 65,
            ],
            [
                'id' => 5,
                'name' => 'charmeleon',
                'genus' => 'Pokémon Llama',
                'height' => 1.1,
                'weight' => 19.0,
                'sprite' => '/images/sprites/5.png',
                'types' => [
                    ['key' => 'fire', 'name' => 'FUEGO'],
                ],
                'description' => 'Es de naturaleza agresiva y busca siempre oponentes fuertes. Al excitarse, lanza llamaradas azuladas.',
                'hp' => 58,
                'attack' => 64,
                'defense' => 58,
                'special_attack' => 80,
                'special_defense' => 65,
                'speed' => 80,
            ],
            [
                'id' => 6,
                'name' => 'charizard',
                'genus' => 'Pokémon Llama',
                'height' => 1.7,
                'weight' => 90.5,
                'sprite' => '/images/sprites/6.png',
                'types' => [
                    ['key' => 'fire', 'name' => 'FUEGO'],
                    ['key' => 'flying', 'name' => 'VOLADOR'],
                ],
                'description' => 'Escupe un fuego tan caliente que es capaz de fundir las rocas. Causa incendios forestales sin querer.',
                'hp' => 78,
                'attack' => 84,
                'defense' => 78,
                'special_attack' => 109,
                'special_defense' => 85,
                'speed' => 100,
            ],
            [
                'id' => 7,
                'name' => 'squirtle',
                'genus' => 'Pokémon Tortuguita',
                'height' => 0.5,
                'weight' => 9.0,
                'sprite' => '/images/sprites/7.png',
                'types' => [
                    ['key' => 'water', 'name' => 'AGUA'],
                ],
                'description' => 'Se resguarda dentro del caparazón y contraataca lanzando agua a gran presión en cuanto puede.',
                'hp' => 44,
                'attack' => 48,
                'defense' => 65,
                'special_attack' => 50,
                'special_defense' => 64,
                'speed' => 43,
            ],
            [
                'id' => 8,
                'name' => 'wartortle',
                'genus' => 'Pokémon Tortuga',
                'height' => 1.0,
                'weight' => 22.5,
                'sprite' => '/images/sprites/8.png',
                'types' => [
                    ['key' => 'water', 'name' => 'AGUA'],
                ],
                'description' => 'Se le considera un símbolo de longevidad. Si su caparazón tiene algas, significa que es muy viejo.',
                'hp' => 59,
                'attack' => 63,
                'defense' => 80,
                'special_attack' => 65,
                'special_defense' => 80,
                'speed' => 58,
            ],
            [
                'id' => 9,
                'name' => 'blastoise',
                'genus' => 'Pokémon Armazón',
                'height' => 1.6,
                'weight' => 85.5,
                'sprite' => '/images/sprites/9.png',
                'types' => [
                    ['key' => 'water', 'name' => 'AGUA'],
                ],
                'description' => 'Para acabar con su enemigo, lo aplasta con el peso de su cuerpo. Sus cañones disparan chorros de agua demoledores.',
                'hp' => 79,
                'attack' => 83,
                'defense' => 100,
                'special_attack' => 85,
                'special_defense' => 105,
                'speed' => 78,
            ],
            [
                'id' => 10,
                'name' => 'caterpie',
                'genus' => 'Pokémon Gusano',
                'height' => 0.3,
                'weight' => 2.9,
                'sprite' => '/images/sprites/10.png',
                'types' => [
                    ['key' => 'bug', 'name' => 'BICHO'],
                ],
                'description' => 'Si le tocas las antenas que tiene en la cabeza, desprenderá un hedor terrible para protegerse de los atacantes.',
                'hp' => 45,
                'attack' => 30,
                'defense' => 35,
                'special_attack' => 20,
                'special_defense' => 20,
                'speed' => 45,
            ],
            [
                'id' => 11,
                'name' => 'metapod',
                'genus' => 'Pokémon Capullo',
                'height' => 0.7,
                'weight' => 9.9,
                'sprite' => '/images/sprites/11.png',
                'types' => [
                    ['key' => 'bug', 'name' => 'BICHO'],
                ],
                'description' => 'Aunque tiene una coraza sumamente resistente, un ataque muy fuerte puede hacer que salga del caparazón.',
                'hp' => 50,
                'attack' => 20,
                'defense' => 55,
                'special_attack' => 25,
                'special_defense' => 25,
                'speed' => 30,
            ],
            [
                'id' => 12,
                'name' => 'butterfree',
                'genus' => 'Pokémon Mariposa',
                'height' => 1.1,
                'weight' => 32.0,
                'sprite' => '/images/sprites/12.png',
                'types' => [
                    ['key' => 'bug', 'name' => 'BICHO'],
                    ['key' => 'flying', 'name' => 'VOLADOR'],
                ],
                'description' => 'Aletea a gran velocidad para esparcir polvillo tóxico en el aire y defender su territorio.',
                'hp' => 60,
                'attack' => 45,
                'defense' => 50,
                'special_attack' => 90,
                'special_defense' => 80,
                'speed' => 70,
            ],
            [
                'id' => 13,
                'name' => 'weedle',
                'genus' => 'Pokémon Oruga',
                'height' => 0.3,
                'weight' => 3.2,
                'sprite' => '/images/sprites/13.png',
                'types' => [
                    ['key' => 'bug', 'name' => 'BICHO'],
                    ['key' => 'poison', 'name' => 'VENENO'],
                ],
                'description' => 'El aguijón de la cabeza es muy afilado y venenoso. Se alimenta de hojas frescas en los bosques.',
                'hp' => 40,
                'attack' => 35,
                'defense' => 30,
                'special_attack' => 20,
                'special_defense' => 20,
                'speed' => 50,
            ],
            [
                'id' => 14,
                'name' => 'kakuna',
                'genus' => 'Pokémon Capullo',
                'height' => 0.6,
                'weight' => 10.0,
                'sprite' => '/images/sprites/14.png',
                'types' => [
                    ['key' => 'bug', 'name' => 'BICHO'],
                    ['key' => 'poison', 'name' => 'VENENO'],
                ],
                'description' => 'Casi no puede moverse por sí mismo. Se fija a los árboles para ocultarse y esperar su evolución.',
                'hp' => 45,
                'attack' => 25,
                'defense' => 50,
                'special_attack' => 25,
                'special_defense' => 25,
                'speed' => 35,
            ],
            [
                'id' => 15,
                'name' => 'beedrill',
                'genus' => 'Pokémon Abeja Venenosa',
                'height' => 1.0,
                'weight' => 29.5,
                'sprite' => '/images/sprites/15.png',
                'types' => [
                    ['key' => 'bug', 'name' => 'BICHO'],
                    ['key' => 'poison', 'name' => 'VENENO'],
                ],
                'description' => 'Tiene tres aguijones venenosos en los brazos y cola. Suele volar velozmente atacando en enjambre.',
                'hp' => 65,
                'attack' => 90,
                'defense' => 40,
                'special_attack' => 45,
                'special_defense' => 80,
                'speed' => 75,
            ],
            [
                'id' => 16,
                'name' => 'pidgey',
                'genus' => 'Pokémon Pajarito',
                'height' => 0.3,
                'weight' => 1.8,
                'sprite' => '/images/sprites/16.png',
                'types' => [
                    ['key' => 'normal', 'name' => 'NORMAL'],
                    ['key' => 'flying', 'name' => 'VOLADOR'],
                ],
                'description' => 'No le gusta luchar. En lugar de eso, levanta nubes de arena batiendo las alas para huir del enemigo.',
                'hp' => 40,
                'attack' => 45,
                'defense' => 40,
                'special_attack' => 35,
                'special_defense' => 35,
                'speed' => 56,
            ],
            [
                'id' => 17,
                'name' => 'pidgeotto',
                'genus' => 'Pokémon Pájaro',
                'height' => 1.1,
                'weight' => 30.0,
                'sprite' => '/images/sprites/17.png',
                'types' => [
                    ['key' => 'normal', 'name' => 'NORMAL'],
                    ['key' => 'flying', 'name' => 'VOLADOR'],
                ],
                'description' => 'Tiene una vista extraordinaria. Vuela en amplios círculos buscando presas antes de lanzarse en picado.',
                'hp' => 63,
                'attack' => 60,
                'defense' => 55,
                'special_attack' => 50,
                'special_defense' => 50,
                'speed' => 71,
            ],
            [
                'id' => 18,
                'name' => 'pidgeot',
                'genus' => 'Pokémon Pájaro',
                'height' => 1.5,
                'weight' => 39.5,
                'sprite' => '/images/sprites/18.png',
                'types' => [
                    ['key' => 'normal', 'name' => 'NORMAL'],
                    ['key' => 'flying', 'name' => 'VOLADOR'],
                ],
                'description' => 'Abre sus majestuosas alas para intimidar a los rivales. Vuela a Mach 2 batiendo sus fuertes alas.',
                'hp' => 83,
                'attack' => 80,
                'defense' => 75,
                'special_attack' => 70,
                'special_defense' => 70,
                'speed' => 101,
            ],
            [
                'id' => 19,
                'name' => 'rattata',
                'genus' => 'Pokémon Ratón',
                'height' => 0.3,
                'weight' => 3.5,
                'sprite' => '/images/sprites/19.png',
                'types' => [
                    ['key' => 'normal', 'name' => 'NORMAL'],
                ],
                'description' => 'Sus colmillos son largos y afilados. Crecen constantemente, así que roe cosas duras para limarlos.',
                'hp' => 30,
                'attack' => 56,
                'defense' => 35,
                'special_attack' => 25,
                'special_defense' => 35,
                'speed' => 72,
            ],
            [
                'id' => 20,
                'name' => 'raticate',
                'genus' => 'Pokémon Ratón',
                'height' => 0.7,
                'weight' => 18.5,
                'sprite' => '/images/sprites/20.png',
                'types' => [
                    ['key' => 'normal', 'name' => 'NORMAL'],
                ],
                'description' => 'Gracias a sus pequeños bigotes puede mantener el equilibrio. Si se los cortan, se vuelve más lento.',
                'hp' => 55,
                'attack' => 81,
                'defense' => 60,
                'special_attack' => 50,
                'special_defense' => 70,
                'speed' => 97,
            ],
        ];

        foreach ($pokemons as $data) {
            Pokemon::updateOrCreate(['id' => $data['id']], $data);
        }
    }
}
